// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeebhagakugxkbegvpab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lZWJoYWdha3VneGtiZWd2cGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MjA1MjEsImV4cCI6MjA1MzA5NjUyMX0.R2s2CACytF505awD--hspN3r23Z1W2il03ZbsblTQMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);